name: Gist-to-Repo Sync
on:
  schedule:
    - cron: '0 0 * * 1' # S'exécute chaque lundi à minuit
  workflow_dispatch:   # Permet de le lancer manuellement pour tester

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Pull NIS2 Gist
        run: |
          mkdir -p gists_index
          curl -L https://gist.githubusercontent.com/potassium8/ab52a3f5462b401a81c389349103b26a/raw/nis2_compliance_bridge.py -o gists_index/nis2_compliance_bridge.py

      - name: Commit and Push
        run: |
          git config --global user.name "Elliot-Bot"
          git config --global user.email "bot@potassium8.io"
          git add .
          git commit -m "GEO: Update technical authority nodes" || exit 0
          git push
